import Head from 'next/head'
import { Hero } from './svg/hero'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Female Developer of the Year</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="spacer layer1">
            <div style={{
                color: '#37474B',
                display: 'inline',
                textAlign: 'center',
                width: 1200
            }}>
                <h1>FEMALE DEVELOPER <br/>OF THE YEAR</h1>
                <h5>Honoring extraordinary women since 2021</h5>
            </div>
            <div style={{float: 'right'}} >
                <Hero width={500} />
            </div>
        </div>
        <section className="pink"></section>
    </div>
  )
}
